### Applying Filtering, Ordering and Grouping to Queries

In [1]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///census.sqlite')
connection = engine.connect()

In [2]:
from sqlalchemy import Table, MetaData, select
metadata = MetaData()
census = Table('census', metadata, autoload=True, autoload_with=engine)
stmt = select([census])

In [3]:
stmt = stmt.where(census.columns.state == 'California')
results = connection.execute(stmt).fetchall()

In [4]:
for result in results[:5]:
    print(result.state, result.age)

California 0
California 1
California 2
California 3
California 4

### Where Clauses
- Restrict data returned by a query based on boolean conditions
- Compare a column against a value or another column
- Often used comparisions: '==', '<=', '>=', '!='

### Expressions
- Provide more complex conditions than simple operators
- Eg `in_()`, `like()`, `between()`
- Many more in documentation
- Available as method on a Column

In [5]:
stmt = select([census])
stmt = stmt.where(
            census.columns.state.startswith('New'))
for result in connection.execute(stmt):
    print(result.state, result.pop2000)

New Jersey 56983
New Jersey 56686
New Jersey 57011
New Jersey 57912
New Jersey 59359
New Jersey 60392
New Jersey 60739
New Jersey 61579
New Jersey 62089
New Jersey 63384
New Jersey 64593
New Jersey 62494
New Jersey 60570
New Jersey 58189
New Jersey 57931
New Jersey 56752
New Jersey 55887
New Jersey 56712
New Jersey 53265
New Jersey 48344
New Jersey 49564
New Jersey 48141
New Jersey 48353
New Jersey 49130
New Jersey 48723
New Jersey 51092
New Jersey 50357
New Jersey 52179
New Jersey 55938
New Jersey 60638
New Jersey 64220
New Jersey 61484
New Jersey 61927
New Jersey 63487
New Jersey 66737
New Jersey 71274
New Jersey 71449
New Jersey 71026
New Jersey 71811
New Jersey 72043
New Jersey 73665
New Jersey 70514
New Jersey 69835
New Jersey 68650
New Jersey 65564
New Jersey 65529
New Jersey 61817
New Jersey 59206
New Jersey 56977
New Jersey 55780
New Jersey 56235
New Jersey 53235
New Jersey 54900
New Jersey 58013
New Jersey 43584
New Jersey 42959
New Jersey 42179
New Jersey 45575
New Jersey 38376
New Jersey 34722
New Jersey 34278
New Jersey 32730
New Jersey 31589
New Jersey 29440
New Jersey 28747
New Jersey 27751
New Jersey 26129
New Jersey 26479
New Jersey 26076
New Jersey 25811
New Jersey 26370
New Jersey 24801
New Jersey 24358
New Jersey 23724
New Jersey 22304
New Jersey 21663
New Jersey 20280
New Jersey 18958
New Jersey 17839
New Jersey 17030
New Jersey 15262
New Jersey 12609
New Jersey 12104
New Jersey 10004
New Jersey 8864
New Jersey 39309
New Jersey 54679
New Jersey 53913
New Jersey 54744
New Jersey 55427
New Jersey 56860
New Jersey 57486
New Jersey 57751
New Jersey 58696
New Jersey 59465
New Jersey 60277
New Jersey 61606
New Jersey 59279
New Jersey 57384
New Jersey 55913
New Jersey 54804
New Jersey 54208
New Jersey 52815
New Jersey 52918
New Jersey 48383
New Jersey 45910
New Jersey 47658
New Jersey 46601
New Jersey 46518
New Jersey 47909
New Jersey 47751
New Jersey 49805
New Jersey 50344
New Jersey 52524
New Jersey 56102
New Jersey 61685
New Jersey 64873
New Jersey 62665
New Jersey 63572
New Jersey 65517
New Jersey 68457
New Jersey 72558
New Jersey 73865
New Jersey 73266
New Jersey 72927
New Jersey 73816
New Jersey 75226
New Jersey 73159
New Jersey 72371
New Jersey 71100
New Jersey 68286
New Jersey 67763
New Jersey 64313
New Jersey 62759
New Jersey 60526
New Jersey 59877
New Jersey 60058
New Jersey 57978
New Jersey 58637
New Jersey 62757
New Jersey 47727
New Jersey 45851
New Jersey 45758
New Jersey 49139
New Jersey 42678
New Jersey 38667
New Jersey 38032
New Jersey 35600
New Jersey 35577
New Jersey 33562
New Jersey 32452
New Jersey 32848
New Jersey 31080
New Jersey 31588
New Jersey 32232
New Jersey 32391
New Jersey 33124
New Jersey 31678
New Jersey 32246
New Jersey 31706
New Jersey 30619
New Jersey 31196
New Jersey 30070
New Jersey 28748
New Jersey 27658
New Jersey 27035
New Jersey 25439
New Jersey 21730
New Jersey 21220
New Jersey 19121
New Jersey 17164
New Jersey 98078
New York 126237
New York 124008
New York 124725
New York 126697
New York 131357
New York 133095
New York 134203
New York 137986
New York 139455
New York 142454
New York 145621
New York 138746
New York 135565
New York 132288
New York 132388
New York 131959
New York 130189
New York 132566
New York 132672
New York 133654
New York 132121
New York 126166
New York 123215
New York 121282
New York 118953
New York 123151
New York 118727
New York 122359
New York 128651
New York 140687
New York 149558
New York 139477
New York 138911
New York 139031
New York 145440
New York 156168
New York 153840
New York 152078
New York 150765
New York 152606
New York 159345
New York 148628
New York 147892
New York 144195
New York 139354
New York 141953
New York 131875
New York 128767
New York 125406
New York 124155
New York 125955
New York 118542
New York 118532
New York 124418
New York 95025
New York 92652
New York 90096
New York 95340
New York 83273
New York 77213
New York 77054
New York 72212
New York 70967
New York 66461
New York 64361
New York 64385
New York 58819
New York 58176
New York 57310
New York 57057
New York 57761
New York 53775
New York 53568
New York 51263
New York 48440
New York 46702
New York 43508
New York 40730
New York 37950
New York 35774
New York 32453
New York 26803
New York 25041
New York 21687
New York 18873
New York 88366
New York 120355
New York 118219
New York 119577
New York 121029
New York 125247
New York 128227
New York 128428
New York 131161
New York 133646
New York 135746
New York 138287
New York 131904
New York 129028
New York 126571
New York 125682
New York 125409
New York 122770
New York 123978
New York 125307
New York 127956
New York 129184
New York 124575
New York 123701
New York 124108
New York 122624
New York 127474
New York 123033
New York 128125
New York 134795
New York 146832
New York 152973
New York 144001
New York 143930
New York 144653
New York 151147
New York 159228
New York 159999
New York 157911
New York 156103
New York 159284
New York 163331
New York 155353
New York 153688
New York 151615
New York 146774
New York 148318
New York 139802
New York 138062
New York 134107
New York 134399
New York 136630
New York 130843
New York 130196
New York 136064
New York 106579
New York 104847
New York 101857
New York 108406
New York 94346
New York 88584
New York 88932
New York 82899
New York 82172
New York 77171
New York 76032
New York 76498
New York 70465
New York 71088
New York 70847
New York 71377
New York 74378
New York 70611
New York 70513
New York 69156
New York 68042
New York 68410
New York 64971
New York 61287
New York 58911
New York 56865
New York 54553
New York 46381
New York 45599
New York 40525
New York 37436
New York 226378
New Hampshire 7302
New Hampshire 7665
New Hampshire 7703
New Hampshire 8112
New Hampshire 8278
New Hampshire 8668
New Hampshire 8680
New Hampshire 9049
New Hampshire 9174
New Hampshire 9653
New Hampshire 9912
New Hampshire 9533
New Hampshire 9544
New Hampshire 9352
New Hampshire 9399
New Hampshire 9273
New Hampshire 8813
New Hampshire 8881
New Hampshire 8812
New Hampshire 8539
New Hampshire 7752
New Hampshire 7459
New Hampshire 6923
New Hampshire 6256
New Hampshire 5938
New Hampshire 6365
New Hampshire 6428
New Hampshire 6675
New Hampshire 7423
New Hampshire 8150
New Hampshire 8529
New Hampshire 8499
New Hampshire 8592
New Hampshire 8971
New Hampshire 9305
New Hampshire 10164
New Hampshire 10464
New Hampshire 10783
New Hampshire 10819
New Hampshire 11414
New Hampshire 11448
New Hampshire 11412
New Hampshire 11283
New Hampshire 11075
New Hampshire 10639
New Hampshire 10502
New Hampshire 10120
New Hampshire 9972
New Hampshire 9542
New Hampshire 9133
New Hampshire 9113
New Hampshire 9019
New Hampshire 9018
New Hampshire 9661
New Hampshire 6578
New Hampshire 6633
New Hampshire 6839
New Hampshire 6861
New Hampshire 5955
New Hampshire 5350
New Hampshire 5116
New Hampshire 4755
New Hampshire 4660
New Hampshire 4384
New Hampshire 4273
New Hampshire 4294
New Hampshire 4062
New Hampshire 3863
New Hampshire 3919
New Hampshire 3713
New Hampshire 3752
New Hampshire 3503
New Hampshire 3305
New Hampshire 3194
New Hampshire 3010
New Hampshire 2954
New Hampshire 2671
New Hampshire 2557
New Hampshire 2394
New Hampshire 2245
New Hampshire 1980
New Hampshire 1795
New Hampshire 1527
New Hampshire 1334
New Hampshire 1219
New Hampshire 5137
New Hampshire 6860
New Hampshire 7124
New Hampshire 7431
New Hampshire 7507
New Hampshire 7821
New Hampshire 8084
New Hampshire 8228
New Hampshire 8543
New Hampshire 8928
New Hampshire 9294
New Hampshire 9369
New Hampshire 9312
New Hampshire 9263
New Hampshire 8973
New Hampshire 9067
New Hampshire 8668
New Hampshire 8356
New Hampshire 8423
New Hampshire 8503
New Hampshire 8834
New Hampshire 8217
New Hampshire 7722
New Hampshire 6769
New Hampshire 6021
New Hampshire 5971
New Hampshire 6450
New Hampshire 6365
New Hampshire 6985
New Hampshire 7575
New Hampshire 8323
New Hampshire 8682
New Hampshire 8677
New Hampshire 8618
New Hampshire 9157
New Hampshire 9632
New Hampshire 10474
New Hampshire 11036
New Hampshire 11190
New Hampshire 11171
New Hampshire 11698
New Hampshire 11597
New Hampshire 11419
New Hampshire 11312
New Hampshire 11231
New Hampshire 10496
New Hampshire 10592
New Hampshire 10303
New Hampshire 10000
New Hampshire 9608
New Hampshire 9112
New Hampshire 9068
New Hampshire 9058
New Hampshire 9151
New Hampshire 9553
New Hampshire 6655
New Hampshire 6640
New Hampshire 6584
New Hampshire 6981
New Hampshire 6021
New Hampshire 5319
New Hampshire 5252
New Hampshire 4876
New Hampshire 4777
New Hampshire 4576
New Hampshire 4652
New Hampshire 4556
New Hampshire 4134
New Hampshire 4240
New Hampshire 4232
New Hampshire 4131
New Hampshire 4338
New Hampshire 4005
New Hampshire 4097
New Hampshire 4145
New Hampshire 3878
New Hampshire 3957
New Hampshire 3558
New Hampshire 3549
New Hampshire 3433
New Hampshire 3400
New Hampshire 3088
New Hampshire 2801
New Hampshire 2663
New Hampshire 2379
New Hampshire 2237
New Hampshire 13312
New Mexico 13560
New Mexico 13293
New Mexico 13001
New Mexico 12904
New Mexico 13332
New Mexico 13642
New Mexico 13910
New Mexico 14408
New Mexico 14551
New Mexico 14866
New Mexico 15259
New Mexico 14874
New Mexico 14927
New Mexico 15239
New Mexico 15089
New Mexico 15310
New Mexico 15222
New Mexico 15232
New Mexico 14493
New Mexico 13774
New Mexico 13160
New Mexico 12122
New Mexico 11588
New Mexico 11512
New Mexico 10832
New Mexico 10935
New Mexico 10919
New Mexico 10875
New Mexico 11239
New Mexico 11713
New Mexico 12146
New Mexico 11498
New Mexico 11102
New Mexico 11194
New Mexico 11586
New Mexico 12861
New Mexico 13156
New Mexico 13594
New Mexico 13760
New Mexico 13842
New Mexico 14187
New Mexico 13760
New Mexico 13725
New Mexico 13844
New Mexico 13183
New Mexico 13446
New Mexico 12976
New Mexico 12673
New Mexico 12224
New Mexico 12342
New Mexico 12443
New Mexico 11814
New Mexico 11420
New Mexico 11886
New Mexico 8960
New Mexico 9087
New Mexico 8689
New Mexico 8960
New Mexico 7859
New Mexico 7497
New Mexico 7384
New Mexico 7020
New Mexico 6897
New Mexico 6594
New Mexico 6424
New Mexico 6533
New Mexico 6072
New Mexico 5962
New Mexico 5935
New Mexico 5648
New Mexico 5788
New Mexico 5199
New Mexico 4988
New Mexico 4745
New Mexico 4477
New Mexico 4299
New Mexico 4142
New Mexico 3787
New Mexico 3622
New Mexico 3310
New Mexico 2985
New Mexico 2460
New Mexico 2271
New Mexico 1990
New Mexico 1788
New Mexico 7749
New Mexico 13171
New Mexico 12869
New Mexico 12623
New Mexico 12671
New Mexico 13016
New Mexico 13130
New Mexico 13466
New Mexico 13759
New Mexico 14102
New Mexico 14538
New Mexico 14699
New Mexico 14425
New Mexico 14233
New Mexico 14410
New Mexico 14445
New Mexico 14602
New Mexico 14325
New Mexico 14426
New Mexico 14001
New Mexico 13382
New Mexico 13136
New Mexico 12074
New Mexico 11672
New Mexico 11355
New Mexico 11186
New Mexico 11179
New Mexico 10982
New Mexico 11166
New Mexico 11677
New Mexico 12066
New Mexico 12322
New Mexico 11723
New Mexico 11448
New Mexico 11619
New Mexico 12163
New Mexico 13475
New Mexico 13636
New Mexico 14283
New Mexico 14312
New Mexico 14744
New Mexico 14956
New Mexico 14320
New Mexico 14450
New Mexico 14488
New Mexico 13943
New Mexico 14157
New Mexico 13692
New Mexico 13575
New Mexico 13297
New Mexico 12740
New Mexico 12677
New Mexico 12302
New Mexico 12032
New Mexico 12565
New Mexico 9425
New Mexico 9651
New Mexico 9450
New Mexico 9428
New Mexico 8747
New Mexico 8054
New Mexico 8007
New Mexico 7732
New Mexico 7532
New Mexico 7263
New Mexico 6875
New Mexico 7143
New Mexico 6471
New Mexico 6489
New Mexico 6686
New Mexico 6332
New Mexico 6330
New Mexico 5877
New Mexico 5974
New Mexico 5739
New Mexico 5549
New Mexico 5568
New Mexico 5243
New Mexico 4758
New Mexico 4849
New Mexico 4407
New Mexico 3942
New Mexico 3421
New Mexico 3247
New Mexico 2946
New Mexico 2732
New Mexico 15879

### Conjunctions
- Allow us to have multiple criteria in a where clause
- Eg `and_()`, `not_()`, `or_()`

In [6]:
from sqlalchemy import or_
stmt = select([census])
stmt = stmt.where(
            or_(census.columns.state == 'California',
               census.columns.state == 'New York'
    )
)

In [7]:
for result in connection.execute(stmt):
    print(result.state, result.sex)

New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
New York M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California M
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
California F
New York M
New York M
New York M
New York M
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F
New York F

In [8]:
# # Import create_engine function
# from sqlalchemy import create_engine

# # Create an engine to the census database
# engine = create_engine('postgresql+psycopg2://student:datacamp@postgresql.csrrinzqubik.us-east-1.rds.amazonaws.com:5432/census')

# # Use the .table_names() method on the engine to print the table names
# print(engine.table_names())

In [12]:
# Create a select query: stmt
stmt = select([census])

# Add a where clause to filter the results to only those for New York
stmt = stmt.where(census.columns.state == 'New York')

# Execute the query to retrieve all the data returned: results
results = connection.execute(stmt).fetchall()

# Loop over the results and print the age, sex, and pop2008
for result in results:
    print(result.age, result.sex, result.pop2008)

0 M 128088
1 M 125649
2 M 121615
3 M 120580
4 M 122482
5 M 121205
6 M 120089
7 M 122355
8 M 118653
9 M 117369
10 M 118810
11 M 121121
12 M 126338
13 M 128713
14 M 129812
15 M 134463
16 M 136569
17 M 140114
18 M 156892
19 M 147556
20 M 146611
21 M 141932
22 M 138557
23 M 136150
24 M 132383
25 M 141850
26 M 129603
27 M 131419
28 M 127224
29 M 122449
30 M 126404
31 M 126124
32 M 123362
33 M 126486
34 M 120030
35 M 123017
36 M 127076
37 M 136270
38 M 144715
39 M 135027
40 M 135355
41 M 132905
42 M 140025
43 M 151555
44 M 149030
45 M 148147
46 M 146692
47 M 147648
48 M 155155
49 M 144287
50 M 143466
51 M 139630
52 M 133939
53 M 136723
54 M 125953
55 M 122478
56 M 118070
57 M 115823
58 M 117177
59 M 108293
60 M 106825
61 M 113681
62 M 83763
63 M 81226
64 M 76961
65 M 82242
66 M 70423
67 M 64117
68 M 63657
69 M 58801
70 M 57609
71 M 53231
72 M 51132
73 M 50696
74 M 44822
75 M 43592
76 M 41900
77 M 40417
78 M 40241
79 M 35941
80 M 34659
81 M 32022
82 M 28890
83 M 27217
84 M 23879
85 M 124478
0 F 122194
1 F 119661
2 F 116413
3 F 114877
4 F 116936
5 F 116051
6 F 115186
7 F 116951
8 F 113279
9 F 111919
10 F 113891
11 F 115607
12 F 120156
13 F 123797
14 F 124343
15 F 127635
16 F 130769
17 F 134311
18 F 150772
19 F 142871
20 F 141831
21 F 142302
22 F 138703
23 F 138084
24 F 135339
25 F 141601
26 F 130002
27 F 129600
28 F 129868
29 F 119821
30 F 125047
31 F 127486
32 F 123742
33 F 126908
34 F 121824
35 F 124485
36 F 130377
37 F 140890
38 F 148408
39 F 137936
40 F 138561
41 F 139720
42 F 145307
43 F 154437
44 F 154805
45 F 153651
46 F 151107
47 F 154997
48 F 158855
49 F 151022
50 F 149883
51 F 146988
52 F 142566
53 F 144121
54 F 135180
55 F 132338
56 F 127500
57 F 126450
58 F 128713
59 F 121743
60 F 119540
61 F 126847
62 F 96462
63 F 94667
64 F 90185
65 F 97321
66 F 83336
67 F 77404
68 F 77802
69 F 71850
70 F 71451
71 F 66625
72 F 65037
73 F 65719
74 F 58818
75 F 58722
76 F 57584
77 F 56907
78 F 58456
79 F 54136
80 F 52932
81 F 50693
82 F 48206
83 F 47777
84 F 43454
85 F 273476

In [16]:
stmt = select([census])
stmt = stmt.where(in_(states == census.columns.state))
for result in connection.execute(stmt):
    print(result.state, result.pop2000)

NameError: name 'in_' is not defined

In [21]:
states = ['New York', 'California', 'Texas']
# Create a query for the census table: stmt
stmt = select([census])

# Append a where clause to match all the states in_ the list states
stmt = stmt.where(census.columns.state.in_(states))

# Loop over the ResultProxy and print the state and its population in 2000
for result in connection.execute(stmt):
    print(result.state, result.pop2000)

New York 126237
New York 124008
New York 124725
New York 126697
New York 131357
New York 133095
New York 134203
New York 137986
New York 139455
New York 142454
New York 145621
New York 138746
New York 135565
New York 132288
New York 132388
New York 131959
New York 130189
New York 132566
New York 132672
New York 133654
New York 132121
New York 126166
New York 123215
New York 121282
New York 118953
New York 123151
New York 118727
New York 122359
New York 128651
New York 140687
New York 149558
New York 139477
New York 138911
New York 139031
New York 145440
New York 156168
New York 153840
New York 152078
New York 150765
New York 152606
New York 159345
New York 148628
New York 147892
New York 144195
New York 139354
New York 141953
New York 131875
New York 128767
New York 125406
New York 124155
New York 125955
New York 118542
New York 118532
New York 124418
New York 95025
New York 92652
New York 90096
New York 95340
New York 83273
New York 77213
New York 77054
New York 72212
New York 70967
New York 66461
New York 64361
New York 64385
New York 58819
New York 58176
New York 57310
New York 57057
New York 57761
New York 53775
New York 53568
New York 51263
New York 48440
New York 46702
New York 43508
New York 40730
New York 37950
New York 35774
New York 32453
New York 26803
California 252494
California 247978
California 250644
California 257443
California 266855
California 272801
California 274899
California 277580
California 283553
California 285478
California 284518
California 269009
California 262671
California 254889
California 253023
California 251962
California 249220
California 255482
California 252607
California 248356
California 250156
California 238235
California 235718
California 239698
California 240655
California 250964
California 245324
California 251413
California 260869
California 276142
California 293816
California 273159
California 268484
California 263472
California 269607
California 286895
California 284414
California 280861
California 281214
California 278802
California 290332
California 267684
California 268045
California 261885
California 252175
California 255340
California 239126
California 229057
California 219293
California 214700
California 219017
California 203068
California 200466
California 207237
California 160674
California 158483
California 150235
California 150046
California 133017
California 124106
California 121984
California 114331
California 110491
California 102859
California 99345
California 100052
California 91053
California 89634
California 88258
California 87840
California 88575
California 80843
California 79376
California 76365
California 73697
California 72885
California 69738
California 65865
California 62867
California 58012
California 51806
California 43254
California 40083
California 34144
California 30384
California 136442
California 239605
California 236543
California 240010
California 245739
California 254522
California 260264
California 261296
California 264083
California 270447
California 271482
California 270567
California 256656
California 249887
California 242724
California 240752
California 240170
California 233186
California 235767
California 234949
California 233477
California 233532
California 223990
California 222035
California 227742
California 228401
California 238602
California 233133
California 240008
California 249185
California 266010
California 278894
California 260916
California 256168
California 252784
California 256283
California 276234
California 277592
California 276277
California 275129
California 276094
California 283554
California 265614
California 265895
California 263355
California 255016
California 256779
California 244172
California 236211
California 226391
California 221928
California 225414
California 212545
California 208500
California 215228
California 168388
California 166675
California 158368
California 160423
California 142287
California 133235
California 132033
California 123328
California 120982
California 114959
California 111942
California 113547
California 104910
California 103883
California 102061
California 103181
California 106514
California 99453
California 100574
California 99772
California 99390
California 99277
California 95046
California 90193
California 86911
California 81990
California 75849
California 65410
California 61518
California 54748
California 50746
California 294583
New York 25041
New York 21687
New York 18873
New York 88366
New York 120355
New York 118219
New York 119577
New York 121029
New York 125247
New York 128227
New York 128428
New York 131161
New York 133646
New York 135746
New York 138287
New York 131904
New York 129028
New York 126571
New York 125682
New York 125409
New York 122770
New York 123978
New York 125307
New York 127956
New York 129184
New York 124575
New York 123701
New York 124108
New York 122624
New York 127474
New York 123033
New York 128125
New York 134795
New York 146832
New York 152973
New York 144001
New York 143930
New York 144653
New York 151147
New York 159228
New York 159999
New York 157911
New York 156103
New York 159284
New York 163331
New York 155353
New York 153688
New York 151615
New York 146774
New York 148318
New York 139802
New York 138062
New York 134107
New York 134399
New York 136630
New York 130843
New York 130196
New York 136064
New York 106579
New York 104847
New York 101857
New York 108406
New York 94346
New York 88584
New York 88932
New York 82899
New York 82172
New York 77171
New York 76032
New York 76498
New York 70465
New York 71088
New York 70847
New York 71377
New York 74378
New York 70611
New York 70513
New York 69156
New York 68042
New York 68410
New York 64971
New York 61287
New York 58911
New York 56865
New York 54553
New York 46381
New York 45599
New York 40525
New York 37436
New York 226378
Texas 172223
Texas 165635
Texas 165337
Texas 164292
Texas 165785
Texas 166278
Texas 167170
Texas 169210
Texas 171199
Texas 170521
Texas 173734
Texas 167859
Texas 166474
Texas 166014
Texas 166081
Texas 167257
Texas 165881
Texas 171567
Texas 170011
Texas 164671
Texas 163295
Texas 153946
Texas 150839
Texas 152673
Texas 153769
Texas 156739
Texas 153181
Texas 155480
Texas 161048
Texas 165852
Texas 167982
Texas 158505
Texas 153855
Texas 151149
Texas 155095
Texas 164514
Texas 167136
Texas 168668
Texas 167261
Texas 169195
Texas 173212
Texas 164647
Texas 163690
Texas 161774
Texas 154542
Texas 154603
Texas 145891
Texas 141254
Texas 133710
Texas 129998
Texas 128278
Texas 123298
Texas 120815
Texas 126031
Texas 95701
Texas 95537
Texas 93337
Texas 91482
Texas 82603
Texas 76614
Texas 73441
Texas 69422
Texas 67820
Texas 63502
Texas 62593
Texas 62994
Texas 57324
Texas 55581
Texas 54657
Texas 53235
Texas 52902
Texas 49046
Texas 46608
Texas 44784
Texas 42390
Texas 40487
Texas 37785
Texas 35332
Texas 33199
Texas 29635
Texas 27357
Texas 21864
Texas 20249
Texas 16946
Texas 15033
Texas 69392
Texas 164724
Texas 158669
Texas 157386
Texas 157374
Texas 158236
Texas 158722
Texas 160506
Texas 162126
Texas 163788
Texas 163500
Texas 165717
Texas 160176
Texas 159167
Texas 158693
Texas 158580
Texas 159654
Texas 155841
Texas 158372
Texas 156767
Texas 156778
Texas 156625
Texas 147729
Texas 144433
Texas 147865
Texas 146961
Texas 151098
Texas 148823
Texas 151810
Texas 158452
Texas 165252
Texas 164600
Texas 155658
Texas 150518
Texas 148996
Texas 152593
Texas 163350
Texas 167597
Texas 168463
Texas 168421
Texas 169355
Texas 171412
Texas 164244
Texas 163809
Texas 162822
Texas 155226
Texas 155427
Texas 149105
Texas 144081
Texas 136873
Texas 133610
Texas 133121
Texas 127211
Texas 125058
Texas 129694
Texas 99379
Texas 100403
Texas 97778
Texas 95755
Texas 87189
Texas 82764
Texas 79048
Texas 75160
Texas 74358
Texas 70332
Texas 70089
Texas 71266
Texas 65074
Texas 64383
Texas 63639
Texas 62713
Texas 64996
Texas 59894
Texas 58527
Texas 57708
Texas 56446
Texas 55989
Texas 52656
Texas 48993
Texas 47681
Texas 44609
Texas 42132
Texas 35378
Texas 33852
Texas 30076
Texas 27961
Texas 171538

In [22]:
# Import and_
from sqlalchemy import and_

# Build a query for the census table: stmt
stmt = select([census])

# Append a where clause to select only non-male records from California using and_
stmt = stmt.where(
    # The state of California with a non-male sex
    and_(census.columns.state == 'California',
         census.columns.sex != 'M'
         )
)

# Loop over the ResultProxy printing the age and sex
for result in connection.execute(stmt):
    print(result.age , result.sex)

0 F
1 F
2 F
3 F
4 F
5 F
6 F
7 F
8 F
9 F
10 F
11 F
12 F
13 F
14 F
15 F
16 F
17 F
18 F
19 F
20 F
21 F
22 F
23 F
24 F
25 F
26 F
27 F
28 F
29 F
30 F
31 F
32 F
33 F
34 F
35 F
36 F
37 F
38 F
39 F
40 F
41 F
42 F
43 F
44 F
45 F
46 F
47 F
48 F
49 F
50 F
51 F
52 F
53 F
54 F
55 F
56 F
57 F
58 F
59 F
60 F
61 F
62 F
63 F
64 F
65 F
66 F
67 F
68 F
69 F
70 F
71 F
72 F
73 F
74 F
75 F
76 F
77 F
78 F
79 F
80 F
81 F
82 F
83 F
84 F
85 F

### Ordering Query Results

#### Order by Clauses
- Allows us to control the order in which records are returned in the query results
- Available as a method on statements `order_by()`

In [23]:
print(results[:10])

[('New York', 'M', 0, 126237, 128088), ('New York', 'M', 1, 124008, 125649), ('New York', 'M', 2, 124725, 121615), ('New York', 'M', 3, 126697, 120580), ('New York', 'M', 4, 131357, 122482), ('New York', 'M', 5, 133095, 121205), ('New York', 'M', 6, 134203, 120089), ('New York', 'M', 7, 137986, 122355), ('New York', 'M', 8, 139455, 118653), ('New York', 'M', 9, 142454, 117369)]

In [24]:
stmt = select([census.columns.state])
stmt = stmt.order_by(census.columns.state)
results = connection.execute(stmt).fetchall()
print(results[:10])

[('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',)]

#### Order by Descending
- Wrap the column with `desc()` in the `order_by()` clause

#### Order by Multiple
- Just separate multiple columns with a comma
- Orders completely by the first column
- Then if there are duplicates in the first column, orders by the second column
- Repeats until all columns are ordered

In [28]:
stmt = select([census.columns.state, census.columns.sex])
stmt = stmt.order_by(census.columns.state, census.columns.sex)
results = connection.execute(stmt).first()
print(results)

('Alabama', 'F')

In [29]:
# Build a query to select the state column: stmt
stmt = select([census.columns.state])

# Order stmt by the state column
stmt = stmt.order_by(census.columns.state)

# Execute the query and store the results: results
results = connection.execute(stmt).fetchall()

# Print the first 10 results
print(results[:10])

[('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',), ('Alabama',)]

In [30]:
# Import desc
from sqlalchemy import desc

# Build a query to select the state column: stmt
stmt = select([census.columns.state])

# Order stmt by state in descending order: rev_stmt
rev_stmt = stmt.order_by(desc(census.columns.state))

# Execute the query and store the results: rev_results
rev_results = connection.execute(rev_stmt).fetchall()

# Print the first 10 rev_results
print(rev_results[:10])

[('Wyoming',), ('Wyoming',), ('Wyoming',), ('Wyoming',), ('Wyoming',), ('Wyoming',), ('Wyoming',), ('Wyoming',), ('Wyoming',), ('Wyoming',)]

In [31]:
# Build a query to select state and age: stmt
stmt = select([census.columns.state, census.columns.age])

# Append order by to ascend by state and descend by age
stmt = stmt.order_by(census.columns.state, desc(census.columns.age) )

# Execute the statement and store all the records: results
results = connection.execute(stmt).fetchall()

# Print the first 20 results
print(results[:20])

[('Alabama', 85), ('Alabama', 85), ('Alabama', 84), ('Alabama', 84), ('Alabama', 83), ('Alabama', 83), ('Alabama', 82), ('Alabama', 82), ('Alabama', 81), ('Alabama', 81), ('Alabama', 80), ('Alabama', 80), ('Alabama', 79), ('Alabama', 79), ('Alabama', 78), ('Alabama', 78), ('Alabama', 77), ('Alabama', 77), ('Alabama', 76), ('Alabama', 76)]