### What are Glyphs
- Visual shapes
 - Circles, square, triangles
 - Rectangles, lines, wedges
- With properties attached to data
 - coordinates (x,y)
 - size, color, transparency

In [1]:
from bokeh.io import output_file, show
from bokeh.plotting import figure
# plot = figure(plot_width=400, tools='pan,box_zoom')
# plot.circle([1,2,3,4,5], [8,6,5,2,3])
# output_file('circle.html')
# show(plot)

### Glyph properties
- Lists, arrays, sequences of values
- Single fixed values

In [2]:
plot = figure()
plot.circle(x=10, y=[2,5,8,12], size=[10,20,30,40])
output_file('circle.html')
show(plot)

In [6]:
import pandas as pd
df = pd.read_csv('literacy_birth_rate.csv')
df

,Country,Continent,female literacy,fertility,population
0,Chine,ASI,90.5,1.769,1.324655e+09
1,Inde,ASI,50.8,2.682,1.139965e+09
2,USA,NAM,99,2.077,3.040600e+08
3,Indonésie,ASI,88.8,2.132,2.273451e+08
4,Brésil,LAT,90.2,1.827,1.919715e+08
5,Pakistan,ASI,40,3.872,1.661115e+08
6,Bangladesh,ASI,49.8,2.288,1.600001e+08
7,Nigéria,AF,48.8,5.173,1.512123e+08
8,Fédération de Russie,EUR,99.4,1.393,1.419500e+08
9,Japan,ASI,99,1.262,1.277040e+08
10,Mexique,LAT,91.5,2.156,1.063504e+08
11,Philippines,ASI,93.9,3.026,9.034844e+07
12,Viet Nam,ASI,90.2,2.033,8.621078e+07
13,Germany,EUR,99,1.324,8.211010e+07
14,Egypte,AF,57.8,2.816,8.152717e+07
15,Ethiopie,AF,22.8,5.211,8.071343e+07
16,Turquie,ASI,81.3,2.1,7.391426e+07
17,"Iran, République islamique d'",ASI,77.2,1.781,7.195632e+07
18,Thaïlande,ASI,91.5,1.822,6.738638e+07
19,Rép. Démocratique du Congo,AF,56.1,5.908,6.425664e+07
20,France,EUR,99,1.881,6.227743e+07
21,UK,EUR,99,1.852,6.141406e+07
22,Italie,EUR,98.5,1.39,5.983218e+07
23,Myanmar,ASI,89.2,2.281,4.956302e+07
24,Afrique du Sud,AF,88.1,2.505,4.868700e+07
25,South Korea,ASI,96.6,1.224,4.860700e+07
26,Ukraine,EUR,99.6,1.361,4.625820e+07
27,Espagne,EUR,96.9,1.468,4.555572e+07
28,Colombie,LAT,93.4,2.404,4.501210e+07
29,République-Unie de Tanzanie,AF,66.3,5.52,4.248392e+07
...,...,...,...,...,...
152,Malte,EUR,93.5,1.251,4.119500e+05
153,Brunéi Darussalam,ASI,93.3,2.052,3.922800e+05
154,Bahamas,LAT,96.5,3.371,3.376680e+05
155,Iceland,EUR,99,2.093,3.174140e+05
156,Maldives,ASI,98.4,2,3.050270e+05
157,Vanuatu,OCE,79.5,3.883,2.338660e+05
158,Samoa,OCE,98.5,3.852,1.788690e+05
159,Sao Tomé-et-Principe,AF,83.3,3.718,1.601740e+05
160,Aruba,LAT,98,1.732,1.054550e+05
161,Tonga,ASI,99.1,3.928,1.035660e+05
162,NaN,NaN,NaN,NaN,NaN
163,NaN,NaN,NaN,NaN,NaN
164,NaN,NaN,NaN,NaN,NaN
165,NaN,NaN,NaN,NaN,NaN
166,NaN,NaN,NaN,NaN,NaN
167,NaN,NaN,NaN,NaN,NaN
168,NaN,NaN,NaN,NaN,NaN
169,NaN,NaN,NaN,NaN,NaN
170,NaN,NaN,NaN,NaN,NaN
171,NaN,NaN,NaN,NaN,NaN
172,NaN,NaN,NaN,NaN,NaN
173,NaN,NaN,NaN,NaN,NaN
174,NaN,NaN,NaN,NaN,NaN
175,Country,Continent,female literacy,fertility,NaN
176,Antigua-et-Barbuda,NaN,99.4,NaN,NaN
177,Antilles néerlandaises,NaN,96.3,NaN,NaN
178,Iles Caïmanes,NaN,99,NaN,NaN
179,Seychelles,NaN,92.3,NaN,NaN
180,Territoires autonomes palestiniens,NaN,90.9,NaN,NaN
181,WORLD,WORLD,77,NaN,NaN

In [4]:
import numpy as np
female_literacy = np.array(df['female literacy'][:162]).astype('float')
fertility = np.array(df['fertility'][:162]).astype('float')
female_literacy
fertility

array([1.769, 2.682, 2.077, 2.132, 1.827, 3.872, 2.288, 5.173, 1.393,
       1.262, 2.156, 3.026, 2.033, 1.324, 2.816, 5.211, 2.1  , 1.781,
       1.822, 5.908, 1.881, 1.852, 1.39 , 2.281, 2.505, 1.224, 1.361,
       1.468, 2.404, 5.52 , 4.058, 2.223, 4.859, 1.267, 2.342, 1.579,
       6.254, 2.334, 3.961, 6.505, 2.53 , 2.823, 2.498, 2.248, 2.508,
       3.04 , 1.854, 4.22 , 5.1  , 4.967, 1.325, 4.514, 3.173, 2.308,
       4.62 , 4.541, 5.637, 1.926, 1.747, 2.294, 5.841, 5.455, 7.069,
       2.859, 4.018, 2.513, 5.405, 5.737, 3.363, 4.89 , 1.385, 1.505,
       6.081, 1.784, 1.378, 1.45 , 1.841, 1.37 , 2.612, 5.329, 5.33 ,
       3.371, 1.281, 1.871, 2.153, 5.378, 4.45 , 1.46 , 1.436, 1.612,
       3.19 , 2.752, 3.35 , 4.01 , 4.166, 2.642, 2.977, 3.415, 2.295,
       3.019, 2.683, 5.165, 1.849, 1.836, 2.518, 2.43 , 4.528, 1.263,
       1.885, 1.943, 1.899, 1.442, 1.953, 4.697, 1.582, 2.025, 1.841,
       5.011, 1.212, 1.502, 2.516, 1.367, 2.089, 4.388, 1.854, 1.748,
       2.978, 2.152, 2.362, 1.988, 1.426, 3.29 , 3.264, 1.436, 1.393,
       2.822, 4.969, 5.659, 3.24 , 1.693, 1.647, 2.36 , 1.792, 3.45 ,
       1.516, 2.233, 2.563, 5.283, 3.885, 0.966, 2.373, 2.663, 1.251,
       2.052, 3.371, 2.093, 2.   , 3.883, 3.852, 3.718, 1.732, 3.928])

In [5]:
# Import figure from bokeh.plotting
from bokeh.plotting import figure

# Import output_file and show from bokeh.io
from bokeh.io import output_file, show 

# Create the figure: p
p = figure(x_axis_label ='fertility (children per woman)', y_axis_label='female_literacy (% population)')

# Add a circle glyph to the figure p
p.circle(fertility, female_literacy)

# Call the output_file() function and specify the name of the file
output_file('fert_lit.html')

# Display the plot
show(p)

In [13]:
fertility_africa = np.array(df.loc[df['Continent'] == 'AF']['fertility']).astype(float)
female_literacy_africa = np.array(df.loc[df['Continent'] == 'AF']['female literacy']).astype(float)

In [14]:
fertility_latinamerica = np.array(df.loc[df['Continent'] == 'LAT']['fertility']).astype(float)
female_literacy_latinamerica = np.array(df.loc[df['Continent'] == 'LAT']['female literacy']).astype(float)

In [15]:
# Create the figure: p
p = figure(x_axis_label='fertility', y_axis_label='female_literacy (% population)')

# Add a circle glyph to the figure p
p.circle(fertility_latinamerica, female_literacy_latinamerica)

# Add an x glyph to the figure p
p.x(fertility_africa, female_literacy_africa)

# Specify the name of the file
output_file('fert_lit_separate.html')

# Display the plot
show(p)